version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=baoanh
      - MYSQL_DATABASE=baoanh
      - MYSQL_ROOT_PASSWORD=OdQ-c-uItwsrS@25
    ports:
      - '3307:3306'
    expose:
      - 3306
  backend: 
    build: 
      context: ../../Nodejs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      - DB_PORT=3306
      - DB_HOST=db
      - DB_PASSWORD=OdQ-c-uItwsrS@25
     # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
#docker compose -p baoanh-nodejs-mysql up -d